"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { ArrowLeft, Building2, LoaderCircle, Save } from "lucide-react";
import { useRouter } from "next/navigation";
import { apiRequest } from "@/lib/api/client";
import type { Supplier } from "@/types/supplier";

export default function SupplierForm({ supplierId }: { supplierId?: string }) {
  const router = useRouter(); const editing = Boolean(supplierId);
  const [supplier, setSupplier] = useState<Supplier | null>(null); const [loading, setLoading] = useState(editing); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  useEffect(() => { if (!supplierId) return; let active = true; void apiRequest<Supplier>(`/suppliers/${supplierId}`).then((data) => { if (active) setSupplier(data); }).catch((cause: unknown) => { if (active) setError(cause instanceof Error ? cause.message : "Não foi possível carregar o fornecedor."); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [supplierId]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const optional = (name: string) => String(data.get(name) ?? "").trim(); const payload = { legalName: optional("legalName"), tradeName: optional("tradeName"), document: optional("document"), contactName: optional("contactName"), email: optional("email"), phone: optional("phone"), active: data.get("active") === "on", postalCode: optional("postalCode"), street: optional("street"), number: optional("number"), district: optional("district"), city: optional("city"), state: optional("state"), notes: optional("notes") }; try { setSaving(true); setError(""); await apiRequest(editing ? `/suppliers/${supplierId}` : "/suppliers", { method: editing ? "PATCH" : "POST", body: JSON.stringify(payload) }); router.push("/fornecedores"); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível salvar o fornecedor."); } finally { setSaving(false); } }
  if (loading) return <div className="flex min-h-72 items-center justify-center"><LoaderCircle className="size-5 animate-spin text-violet-600" /></div>;
  if (editing && !supplier) return <div role="alert" className="rounded-xl bg-red-50 p-4 text-xs text-red-700">{error || "Fornecedor não encontrado."}</div>;
  return <section className="mx-auto max-w-5xl"><div className="flex items-start gap-3"><Link href="/fornecedores" aria-label="Voltar para fornecedores" className="flex size-10 items-center justify-center rounded-xl border bg-white"><ArrowLeft className="size-4" /></Link><div><p className="text-[11px] font-bold uppercase tracking-wider text-violet-600">Suprimentos</p><h1 className="mt-1 text-2xl font-black sm:text-3xl">{editing ? "Editar fornecedor" : "Novo fornecedor"}</h1><p className="mt-1 text-xs text-slate-500">Dados comerciais, contato e endereço.</p></div></div><form key={supplier?.id ?? "new"} onSubmit={submit} className="mt-5 space-y-4"><Card title="Identificação" icon={Building2}><div className="grid gap-4 sm:grid-cols-2"><Field label="Razão social" name="legalName" required defaultValue={supplier?.legalName} /><Field label="Nome fantasia" name="tradeName" defaultValue={supplier?.tradeName} /><Field label="CPF ou CNPJ" name="document" defaultValue={supplier?.document} /><Field label="Pessoa de contato" name="contactName" defaultValue={supplier?.contactName} /><Field label="E-mail" name="email" type="email" defaultValue={supplier?.email} /><Field label="Telefone" name="phone" defaultValue={supplier?.phone} /></div><label className="mt-4 flex items-center gap-2 text-xs font-bold text-slate-700"><input type="checkbox" name="active" defaultChecked={supplier?.active ?? true} className="size-4 accent-violet-600" />Fornecedor ativo</label></Card><Card title="Endereço"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field label="CEP" name="postalCode" defaultValue={supplier?.postalCode} /><Field label="Endereço" name="street" defaultValue={supplier?.street} className="lg:col-span-2" /><Field label="Número" name="number" defaultValue={supplier?.number} /><Field label="Bairro" name="district" defaultValue={supplier?.district} /><Field label="Cidade" name="city" defaultValue={supplier?.city} className="lg:col-span-2" /><Field label="Estado" name="state" maxLength={2} defaultValue={supplier?.state} /></div></Card><Card title="Observações"><textarea name="notes" rows={3} maxLength={2000} defaultValue={supplier?.notes ?? ""} className={textareaClass} /></Card>{error && <div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-xs font-semibold text-red-700">{error}</div>}<div className="flex justify-end"><button disabled={saving} className="flex h-11 items-center gap-2 rounded-xl bg-gradient-to-r from-violet-600 to-indigo-600 px-5 text-sm font-bold text-white disabled:opacity-60">{saving ? <LoaderCircle className="size-4 animate-spin" /> : <Save className="size-4" />}Salvar fornecedor</button></div></form></section>;
}
function Card({ title, icon: Icon, children }: { title: string; icon?: typeof Building2; children: React.ReactNode }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-2 border-b border-slate-100 pb-3">{Icon && <Icon className="size-4 text-violet-600" />}<h2 className="text-sm font-bold">{title}</h2></div>{children}</div>; }
function Field({ label, name, type = "text", required, defaultValue, className = "", maxLength }: { label: string; name: string; type?: string; required?: boolean; defaultValue?: string | null; className?: string; maxLength?: number }) { return <label className={className}><span className="mb-1.5 block text-xs font-bold text-slate-700">{label}</span><input name={name} type={type} required={required} maxLength={maxLength} defaultValue={defaultValue ?? ""} className={inputClass} /></label>; }
const inputClass = "h-11 w-full rounded-xl border border-slate-200 px-3.5 text-sm outline-none focus:border-violet-400 focus:ring-4 focus:ring-violet-100";
const textareaClass = "w-full resize-y rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-violet-400 focus:ring-4 focus:ring-violet-100";
